### ISSUE TITLE
Add vlan groups to cisco.ucs.ucs_vnic_template 

### ISSUE THREAD

**Issue by RvD78** [CiscoDevNet/ansible-ucs#13]
Hello,

I know how to add multiple vlans to a vNIC template with vlans_list. But I would like to add a vlan group to a vNIC template.

Is this possible?

Thanks in advance.
Richard

**Comment by movinalot** [comment]
Hi Richard,

There is not a specific module for Managing VLAN Groups. However, it can easily be achieved by using the ucs_managed_objects module

Here is an example playbook that adds

- Organization
- vNIC Template to the Organization
- VLAN Group to the Template

I hope this helps

```
---
# Example Playbook: cisco.ucs.ucs_vnic_template with VLAN Groups
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Add UCS Organization
      cisco.ucs.ucs_org:
        <<: *login_info
        org_name: level1
        parent_org_path: root
        description: level1 org
        state: present
        delegate_to: localhost

    - name: Configure vNIC template
      cisco.ucs.ucs_vnic_template:
        <<: *login_info
        name: vNIC-A
        org_dn: org-root/org-level1
        fabric: A
        vlans_list:
        - name: default
          native: 'yes'
        - name: vlan200
          native: 'no'

    - name: Add VLAN Group
      cisco.ucs.ucs_managed_objects:
        <<: *login_info
        objects:
        - module: ucsmsdk.mometa.fabric.FabricNetGroupRef
          class: FabricNetGroupRef
          properties:
            parent_mo_or_dn: org-root/org-level1/lan-conn-templ-vNIC-A
            name : "{{ item }}"
        state: present
      loop:
        - vlan_group1
        - vlan_group2

    - name: Remove VLAN Group
      cisco.ucs.ucs_managed_objects:
        <<: *login_info
        objects:
        - module: ucsmsdk.mometa.fabric.FabricNetGroupRef
          class: FabricNetGroupRef
          properties:
            parent_mo_or_dn: org-root/org-level1/lan-conn-templ-vNIC-A
            name : "vlan_group1"
        state: absent
```
