### ISSUE TITLE
ucs_vlans add support for vlan groups

### ISSUE THREAD

**Issue by Akasurde** [CiscoDevNet/ansible-ucs#16]
_From @denngie on Jul 19, 2018 09:37_

##### SUMMARY

Would like to see support for vlan group as a parameter in the ucs_vlans module. I think the python code in [this](https://github.com/CiscoUcs/ucsmsdk_samples/blob/master/ucsmsdk_samples/network/vlan.py) example could be useful
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ucs_vlans
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/e600790/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Debian 9.5
##### STEPS TO REPRODUCE

```yaml
- name: Configure VLAN
  ucs_vlans:
    hostname: 172.16.143.150
    username: admin
    password: password
    name: vlan2
    id: '2'
    native: 'yes'
    group: Prod
```

##### EXPECTED RESULTS

VLAN is created and added to the VLAN Group Prod
##### ACTUAL RESULTS

N/A

_Copied from original issue: ansible/ansible#43006_

**Comment by bakrir** [comment]
Just piling on here. We probably should also have the `vnic_template` accept `vlan_groups` as a paramter, for example, instead of specifying each VLAN on a vNIC template like so:
```
- name: Configure vNIC template
  cisco.ucs.ucs_vnic_template:
    hostname: 172.16.143.150
    username: admin
    password: password
    name: vNIC-A
    fabric: A
    vlans_list:
    - name: default
      native: 'yes'
```
Maybe, have a `vlan_group` parameter:
```
- name: Configure vNIC template
  cisco.ucs.ucs_vnic_template:
    hostname: 172.16.143.150
    username: admin
    password: password
    name: vNIC-A
    fabric: A
    vlans_list:
    - name: default
      native: 'yes'
    vlans_groups:
    - name: prod
```

Obviously `vlan_groups` would need to be created prior to this change kicing in (similar to VLANs).
