### ISSUE TITLE
1.11.0+ is extra strict on vlans_list format in ucs_vnic_template

### ISSUE THREAD

**Issue by MallocArray** [CiscoDevNet/ansible-ucs#47]
In 1.10.0 an earlier, I was able to have the `vlans_list` property be a list of multiple items, with some properties that were relevant to the ucs_vnic_template and some that were not.

Starting in 1.11.0 and later, it now only accepts the `vlans_list` to contain name, native, and state, which breaks my current structure.
Is this intentional to only allow those 3 in the list, or can the collection be returned to the functionality previously where it would only use those three parameters, but if more were given, they were just ignored?

I'm currently getting around this by just pinning my collection to 1.10.0 and no further.

Example variable structure:
```yaml
lab_vnic_templates:
  - name: Lab_ESXi_A
    description: VMware Lab ESXi 2 NIC configuration on FI-A
    fabric: A
    redundancy_type: primary
    peer_redundancy_template: Lab_ESXi_B
    mtu: 9000
    mac_pool: MAC_Pool_A
    desired_networks:
      - name: lab-vmware-management
        id: "303"
        native: 'yes'
      - name: lab-vmware-vmotion
        id: "304"
```

Example playbook tasks where I use the same data structure to first create the vlans from the `desired_networks` list, and then add all of them to the vnic template with all of the same information

```yaml
- name: UCS VLANs  # noqa: args[module]
  # Creates a VLAN definition in UCS based on those assigned to a vNIC Template.
  # Looping through each vNIC Template and then through each item in the desired_network list, as item.1
  cisco.ucs.ucs_vlans:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: "{{ item.1.name }}"
    id: "{{ item.1.id }}"
    multicast_policy: "{{ item.1.multicast_policy | default('default') }}"
    state: "{{ item.1.vlan_state | default(omit) }}"
  delegate_to: localhost
  loop: "{{ vnic_templates | subelements('desired_networks', 'skip_missing=True') }}"
  loop_control:
    label: "{{ item.1.name }} - VLAN {{ item.1.id }}"

- name: UCS vNIC template  # noqa: args[module]
  # Adds the desired networks to the VNIC Template that is defined in vnic_templates.yml
  cisco.ucs.ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    fabric: "{{ item.fabric }}"
    redundancy_type: "{{ item.redundancy_type | default('none') }}"
    peer_redundancy_template: "{{ item.peer_redundancy_template | default(omit) }}"
    template_type: "{{ item.template_type | default('updating-template') }}"
    mtu: "{{ item.mtu | default(1500) }}"
    mac_pool: "{{ item.mac_pool | default(omit) }}"
    qos_policy: "{{ item.qos_policy | default(omit) }}"
    network_control_policy: "{{ item.network_control_policy | default('default') }}"
    pin_group: "{{ item.pin_group | default(omit) }}"
    stats_policy: "{{ item.stats_policy | default(omit) }}"
    vlans_list: "{{ item.desired_networks | default(omit) }}"
  delegate_to: localhost
  loop: "{{ vnic_templates }}"
  loop_control:
    label: "{{ item.name }}"
```

Result:
```
failed: [ucs.domain.com -> localhost] (item=Lab_ESXi_A) => {"ansible_loop_var": "item", "changed": false, "item": {"description": "VMware Lab ESXi 2 NIC configuration on FI-A", "desired_networks": [{"id": "303", "name": "lab-vmware-management", "native": "yes"}, {"id": "304", "name": "lab-vmware-vmotion"}], "fabric": "A", "mac_pool": "MAC_Pool_A", "mtu": 9000, "name": "Lab_ESXi_A", "peer_redundancy_template": "Lab_ESXi_B", "redundancy_type": "primary"}, "msg": "Unsupported parameters for (cisco.ucs.ucs_vnic_template) module: vlans_list.id, vlans_list.ip. Supported parameters include: name, native, state."}
```
