### ISSUE TITLE
1.11.0+ is extra strict on vlans_list format in ucs_vnic_template - Continued

### ISSUE THREAD

**Issue by MallocArray** [CiscoDevNet/ansible-ucs#49]
Continuation of #47 as I can't re-open it.

In 1.10.0 an earlier, I was able to have the `vlans_list` property be a list of multiple items, with some properties that were relevant to the ucs_vnic_template and some that were not. We also have some properties that are relevant to other technologies, such as VMware

Starting in 1.11.0 and continuing through 1.15.0, it now only accepts the `vlans_list` to contain fabric, id, multicast_policy, name, native, sharing, state, which breaks my current structure.
Is this intentional to only allow those 7 in the list, or can the collection be returned to the functionality previously where it would only use those three parameters, but if more were given, they were just ignored?

I'm currently getting around this by just pinning my collection to 1.10.0 and no further.

Example variable structure:
```yaml
lab_vnic_templates:
  - name: Lab_ESXi_A
    description: VMware Lab ESXi 2 NIC configuration on FI-A
    fabric: A
    redundancy_type: primary
    peer_redundancy_template: Lab_ESXi_B
    mtu: 9000
    mac_pool: MAC_Pool_A
    desired_networks:
      - name: lab-vmware-management
        id: "303"
        native: 'yes'
      - name: lab-vmware-vmotion
        id: "304"
      - name: public-dmz
        ip: 187.29.2.0_23
        id: "123"
        trunk:
          - netscaler-data
```

Example playbook tasks where I use the same data structure to first create the vlans from the `desired_networks` list, and then add all of them to the vnic template with all of the same information

```yaml
- name: UCS VLANs  # noqa: args[module]
  # Creates a VLAN definition in UCS based on those assigned to a vNIC Template.
  # Looping through each vNIC Template and then through each item in the desired_network list, as item.1
  cisco.ucs.ucs_vlans:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: "{{ item.1.name }}"
    id: "{{ item.1.id }}"
    multicast_policy: "{{ item.1.multicast_policy | default('default') }}"
    state: "{{ item.1.vlan_state | default(omit) }}"
  delegate_to: localhost
  loop: "{{ vnic_templates | subelements('desired_networks', 'skip_missing=True') }}"
  loop_control:
    label: "{{ item.1.name }} - VLAN {{ item.1.id }}"

- name: UCS vNIC template  # noqa: args[module]
  # Adds the desired networks to the VNIC Template that is defined in vnic_templates.yml
  cisco.ucs.ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    fabric: "{{ item.fabric }}"
    redundancy_type: "{{ item.redundancy_type | default('none') }}"
    peer_redundancy_template: "{{ item.peer_redundancy_template | default(omit) }}"
    template_type: "{{ item.template_type | default('updating-template') }}"
    mtu: "{{ item.mtu | default(1500) }}"
    mac_pool: "{{ item.mac_pool | default(omit) }}"
    qos_policy: "{{ item.qos_policy | default(omit) }}"
    network_control_policy: "{{ item.network_control_policy | default('default') }}"
    pin_group: "{{ item.pin_group | default(omit) }}"
    stats_policy: "{{ item.stats_policy | default(omit) }}"
    vlans_list: "{{ item.desired_networks | default(omit) }}"
  delegate_to: localhost
  loop: "{{ vnic_templates }}"
  loop_control:
    label: "{{ item.name }}"
```

Result:
```
failed: [ucs.domain.com -> localhost] (item=Lab_ESXi_A) => {"ansible_loop_var": "item", "changed": false, "item": {"description": "VMware Lab ESXi 2 NIC configuration on FI-A", "desired_networks": [{"id": "303", "name": "lab-vmware-management", "native": "yes"}, {"id": "304", "name": "lab-vmware-vmotion"}], "fabric": "A", "mac_pool": "MAC_Pool_A", "mtu": 9000, "name": "Lab_ESXi_A", "peer_redundancy_template": "Lab_ESXi_B", "redundancy_type": "primary"}, "msg": "Unsupported parameters for (cisco.ucs.ucs_vnic_template) module: vlans_list.ip, vlans_list.trunk. Supported parameters include: fabric, id, multicast_policy, name, native, sharing, state."}
```

With the changes in 1.15.0, I can now include the `native:` option, but we also include the IP range for this VLAN and any VMware portgroup trunks it is a member of.  The IP is used when naming the VMware Port Group.  So it makes sense for us to have all of this together in the same data structure, but with the newer versions of this collection complaining when we have other properties that aren't directly used by the module, it prevents us from upgrading unless we completely restructure our data.

**Comment by dsoper2** [comment]
In order to pass Ansible sanity tests required by https://github.com/CiscoDevNet/ansible-ucs/issues/40, we now have to explicitly list options in the docs and code.  We're able to leverage other modules like UCS vlans for docs/code and mention args aren't used, but there's not a way I know of to support an arbitrary list and still pass the required tests.

**Comment by MallocArray** [comment]
Thank you for the feedback.  After a lot of time, I found a way to support the newer collection and still maintain the same data structure I had been using.


```yaml
- name: UCS vNIC template  # noqa: args[module]
  cisco.ucs.ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: "{{ vnic_template['name'] }}"
    description: "{{ vnic_template['description'] }}"
    fabric: "{{ vnic_template['fabric'] }}"
    redundancy_type: "{{ vnic_template['redundancy_type'] | default('none') }}"
    peer_redundancy_template: "{{ vnic_template['peer_redundancy_template'] | default(omit) }}"
    template_type: "{{ vnic_template['template_type'] | default('updating-template') }}"
    mtu: "{{ vnic_template['mtu'] | default(1500) }}"
    mac_pool: "{{ vnic_template['mac_pool'] | default(omit) }}"
    qos_policy: "{{ vnic_template['qos_policy'] | default(omit) }}"
    network_control_policy: "{{ vnic_template['network_control_policy'] | default('default') }}"
    pin_group: "{{ vnic_template['pin_group'] | default(omit) }}"
    stats_policy: "{{ vnic_template['stats_policy'] | default(omit) }}"
    vlans_list: |  # Only keep the vlan name, state, and present values
      {%- set data = [] %}
      {%- for vlan in vnic_template.desired_networks %}
      {%- set data = data.append({'name': vlan.name, 'state': vlan.state | default(omit), 'native': vlan.native | default(omit)}) %}
      {%- endfor %}
      {{- vlan_list | default([]) + data -}}
  delegate_to: localhost
  loop: "{{ item }}"
  loop_control:
    loop_var: vnic_template
    label: "{{ vnic_template['name'] }}"
  tags:
    - vnic_template
    - vlan_vnic
```
