### ISSUE TITLE
cisco.ucs.ucs_ip_pool not idempotent

### ISSUE THREAD

**Issue by MallocArray** [CiscoDevNet/ansible-ucs#50]
Module cisco.ucs.ucs_ip_pool is showing changed on every execution, even when nothing should be changing.  Suspect it is falsely detecting a change.  Possibly related to the IPv6 section not being filled out.

vars:
```yaml
ip_pool_cimc:
  first_addr: 10.12.34.56
  last_addr: 10.12.34.78
  subnet_mask: 255.255.255.0
  default_gw: 10.12.34.1
  primary_dns: 4.2.2.2
  secondary_dns: 8.8.8.8
```

Task
```yaml
- name: IP Pool - CIMC  # noqa: args[module] ansible-lint detects missing arguments incorrectly
  cisco.ucs.ucs_ip_pool:
    hostname: "{{ inventory_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: ext-mgmt-testing
    description: CIMC IP Pool
    ipv4_blocks:
      - first_addr: "{{ ip_pool_cimc.first_addr }}"
        last_addr: "{{ ip_pool_cimc.last_addr }}"
        subnet_mask: "{{ ip_pool_cimc.subnet_mask }}"
        default_gw: "{{ ip_pool_cimc.default_gw }}"
        primary_dns: "{{ ip_pool_cimc.primary_dns }}"
        secondary_dns: "{{ ip_pool_cimc.secondary_dns }}"
  when: ip_pool_cimc is defined
  delegate_to: localhost
```

Output on second run with -vvvv
```json
    "changed": true,
    "invocation": {
        "module_args": {
            "descr": "CIMC IP Pool",
            "description": "CIMC IP Pool",
            "hostname": "ucs.domain.com",
            "ipv4_blocks": [
                {
                    "default_gw": "10.12.34.1",
                    "first_addr": "10.12.34.56",
                    "last_addr": "10.12.34.78",
                    "primary_dns": "4.2.2.2",
                    "secondary_dns": "8.8.8.8",
                    "state": "present",
                    "subnet_mask": "255.255.255.0"
                }
            ],
            "ipv6_blocks": null,
            "name": "ext-mgmt-testing",
            "order": "default",
            "org_dn": "org-root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "proxy": null,
            "state": "present",
            "use_proxy": true,
            "use_ssl": true,
            "username": "domain\\serviceaccount"
        }
    }
}
```

**Comment by RamblingPSTech** [comment]
# Confirmed Continually Detecting A Change

When `state: present`

## Environment:

Python3.12

|Package |Version|
|---|---|
|ansible|11.4.0|
|ansible-core|2.18.4|
|cffi|1.17.1|
|cryptography|44.0.2|
|Jinja2|3.1.6|
|MarkupSafe|3.0.2|
|packaging|24.2|
|pip|25.0.1|
|pycparser|2.22|
|pyparsing|3.2.3|
|PyYAML|6.0.2|
|resolvelib|1.0.1|
|setuptools|78.1.0|
|six|1.17.0|
|ucsmsdk|0.9.21|
|wheel|0.45.1|

---

## Task:

```yaml
- name: Configure IPv4 and IPv6 address pool
  cisco.ucs.ucs_ip_pool:
    hostname: "{{ ucs_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    name: ip-pool-01
```
---

## Output (-vvv)

```yaml
changed: [ucs.domain.com] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "descr": null,
            "hostname": "ucs.domain.com",
            "ipv4_blocks": null,
            "ipv6_blocks": null,
            "name": "ip-pool-01",
            "order": "default",
            "org_dn": "org-root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "proxy": null,
            "state": "present",
            "use_proxy": true,
            "use_ssl": true,
            "username": "ansible_ucs_user"
        }
    }
}
```
